Iter15
arxon31/metrics-collector pull request #15
Opened 2024-02-06 18:23 UTC by arxon31

2024-02-07 15:39 UTC, bambruysk requested changes
Нужно доработать небольшие замечания

2024-02-07 15:39 UTC, bambruysk commented on internal/agent/agent.go
> +				go a.requestExecutor(ctx, requests, 3)
Лучше не использовать магические значения, а задать это как константу

2024-02-07 15:39 UTC, bambruysk commented on internal/agent/agent.go
> +	}()
заковыристо - горутина которая запускает еще одну горутину. Зачем?

2024-02-07 15:39 UTC, bambruysk commented on internal/agent/agent.go
> +			continue
Здесь стоит либо залоггировать ошибку- либо прерваться и вернуть ошибку из функции

2024-02-07 15:39 UTC, bambruysk commented on internal/agent/agent.go
> +		m.Delta = &val
удобнее  и принято таки конструкции записывать как
m := metric.MetricDTO {
    ID : string(name),
   ... 
}

2024-02-07 15:39 UTC, bambruysk commented on internal/agent/agent.go
> +	req, _ := http.NewRequest("POST", endpoint, bytes.NewBuffer(compressedMetricsBatch))
Не надо игнорировать ошибки

2024-02-10 16:22 UTC, arxon31 commented
Саш, подскажи пожалуйста как можно зарефакторить сервер чтобы избавиться от функционала Dump и Restore в нём? Хочу перенести его в repository, конкретно только к стору который в памяти хранится у нас (map), т.к. если я правильно понимаю, то постгрес это делает своими методами а не по указанию со стороны сервиса в него обращающегося. Ну и по рефакторингу в общем было бы интересно услышать твоё мнение!

2024-02-13 07:24 UTC, bambruysk approved these changes
Принято

2024-02-13 07:24 UTC, bambruysk commented on internal/agent/poller/poller.go
> +	v, _ := mem.VirtualMemory()
Не надо игнорить ошибку тут, даже если она маловероятно, скорее всего если ошибка не nil, то v == nil , а значит паника и все такое

2024-06-29 13:10 UTC, merged