added godocs and example for postjson handler
arxon31/metrics-collector pull request #18
Opened 2024-04-07 17:52 UTC by arxon31

Техдолгом остаются тесты на 40%, постараюсь догнать к концу сдачи спринта

2024-04-16 07:17 UTC, bambruysk requested changes
Нужно добавить сами файлы профилей, ну и тесты

2024-06-04 21:08 UTC, alekstet commented on cmd/agent/main.go
> +func initLogger() *zap.SugaredLogger {
А зачем ты это делаешь в main?
Лучше в папке logger

2024-06-04 21:09 UTC, alekstet commented on cmd/server/main.go
> +	controller := controllers.NewController(mux, storageService, providerService, pingerService, logger, cfg.HashKey)
Сделай логгер глобальным и его не нужно будет прокидывать везде

2024-06-04 21:10 UTC, alekstet commented on internal/agent/service/generator/generator.go
> +		g.logger.Error(err)
Ты несколько раз пишешь g.logger.Error(err)
Может быть можно сделать это по другому

2024-06-04 21:13 UTC, alekstet commented on internal/server/controller/http/v1/controller.go
> +		fmt.Println(err)
Используй логи вместо принтов

2024-06-04 21:14 UTC, alekstet commented on internal/server/controller/http/v2/controller.go
> +			http.Error(w, fmt.Sprintf("can not get metric: %s", err), http.StatusInternalServerError)
Ты получается пользователю покажешь ошибку с внутренней логикой

2024-06-04 21:15 UTC, alekstet approved these changes

2024-06-09 15:48 UTC, merged